---
ops: [train, evaluate]
model: {
    path: /content/gdrive/My Drive/Colab Notebooks/NeuralNetworksForGWAS/deepsea.py,
    class: DeepSEA,
    class_args: {
        sequence_length: 1000,
        n_targets: 1,
    },
    non_strand_specific: mean
}
sampler: !obj:selene_sdk.samplers.IntervalsSampler {
    reference_sequence: !obj:selene_sdk.sequences.Genome {
        # we include relative paths here, but we recommend using absolute
        # paths for future configuration files
        input_path: /content/gdrive/My Drive/Colab Notebooks/NeuralNetworksForGWAS/data/male.hg19.fasta
    },
    features: !obj:selene_sdk.utils.load_features_list {
        input_path: /content/gdrive/My Drive/Colab Notebooks/NeuralNetworksForGWAS/data/distinct_features.txt
    },
    target_path: /content/gdrive/My Drive/Colab Notebooks/NeuralNetworksForGWAS/data/sorted_GM12878_CTCF.bed.gz,
    intervals_path: /content/gdrive/My Drive/Colab Notebooks/NeuralNetworksForGWAS/data/deepsea_TF_intervals.txt,
    seed: 127,
    # A positive example is an 1000bp sequence with at least 1 class/feature annotated to it.
    # A negative sample has no classes/features annotated to the sequence.
    sample_negative: True,
    sequence_length: 1000,
    center_bin_to_predict: 200,
    test_holdout: [chr8, chr9],
    validation_holdout: [chr6, chr7],
    # The feature must take up 50% of the bin (200bp) for it to be considered
    # a feature annotated to that sequence.
    feature_thresholds: 0.5,
    mode: train,
    save_datasets: [validate, test]
}
train_model: !obj:selene_sdk.TrainModel {
    batch_size: 64,
    max_steps: 5000,  # update this value for longer training
    report_stats_every_n_steps: 200,
    n_validation_samples: 32000,
    n_test_samples: 120000,
    cpu_n_threads: 32,
    use_cuda: True,
}
random_seed: 1447
output_dir: /content/gdrive/My Drive/Colab Notebooks/NeuralNetworksForGWAS/training_outputs
create_subdirectory: True
load_test_set: False
